### ISSUE TITLE
tickInterval doesn't work

### ISSUE THREAD

**Issue by szhydkov** [dartungar/obsidian-mermaid#11]
I have an issue with the tickInterval option in Gantt charts. Minimal example:
```
```mermaid
gantt
    title Title
    dateFormat  YYYY-MM-DD
    tickInterval 1w
	
    section Sec
	    task :2023-01-01, 4w
\```
```

(without the last slash) produces 
```
Error parsing Mermaid diagram!

Parse error on line 4:
...-DD	tickInterval 1w	    section Sec	
----------------------^
Expecting 'taskData', got 'NL'
```
It works fine without the option.

Thanks for the great plugin btw!

**Comment by dartungar** [comment]
@szhydkov this looks like Obsidian's Mermaid processor issue. Perhaps it didn't get updated to the latest version? Unfortunately I can't help with this, we'll have to wait until Mermaid in Obsidian itself is updated :(
