### ISSUE TITLE
mindmap graph type

### ISSUE THREAD

**Issue by AIMosta** [dartungar/obsidian-mermaid#12]
Hi, the plugin is amazing. Exactly what I was looking for.
Is it possible to add the "mindmap" graph type to the syntax (The syntax is stable except for the icon integration which is the experimental part: [mindmap page](https://mermaid.js.org/syntax/mindmap.html) )?

**Comment by dartungar** [comment]
@AIMosta I can add it to the toolbar, but we'll have to wait until it gets added into Obsidian's Mermaid support. For now it's not supported :(
![image](https://user-images.githubusercontent.com/36126057/213975581-efb83993-fa4d-4070-82ca-d1ade1900a02.png)

**Comment by AIMosta** [comment]
I understand. Thank you for the explanation. But the plugin still remains amazing 🙂.

**Comment by thesocialdev** [comment]
@dartungar where can I track Obsidian's support for mindmap? If not in this repo, where should it be?
