### ISSUE TITLE
Git graphs unreadable due to colors

### ISSUE THREAD

**Issue by barbu110** [dartungar/obsidian-mermaid#13]
Just installed the plugin (v0.1.1) and tried rendering Git graphs. My Obsidian uses the Default theme. Regular top-down graphs look ok and readable, but the Git graph is unreadable:

![image](https://user-images.githubusercontent.com/7272395/215330744-7f7371ec-3f62-462a-abcf-7212009a5923.png)

I tried setting another theme as per the library's documentation (see [docs](https://mermaid.js.org/syntax/gitgraph.html#dark-theme)), but I'm getting an error, seems the CSS syntax they define is not supported:

```
Error parsing Mermaid diagram!

Unsupported color format: "var(--background-primary-alt)"
```

**Comment by dartungar** [comment]
@barbu110 I have no control over (or at least don't plan to interfere with) Obsidian's Mermaid support. All the plugin does is create a convenient way to add diagrams as text. Perhaps you should address the question to official forums?
