### ISSUE TITLE
Installation failed on Android

### ISSUE THREAD

**Issue by dvansoye** [dartungar/obsidian-mermaid#14]
Hi,
I got an error when I tried to install mermaid tools on Android.

I got the following error:

Failed to install plugin "Mermaid Tools"

Then, I looked in the console by connecting my Android phone to a Windows device. This is what it said:

app.js:1 Error: Request failed, status 404
    at new t (app.js:1:699823)
    at iw (app.js:1:700015)
    at app.js:1:700583
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)

Does the mermaid tools plug in work with mobile?

Is there more research that I can do in order to help?

Thanks in advance!

**Comment by dartungar** [comment]
@dvansoye Mermaid Tools uses Obsidian API v.1.1.0 (it's required for some editor tricks), so we'll have to wait for devs to update the mobile app! Nothing we can do about it right now :(
