### ISSUE TITLE
Error parsing Mermaid diagram!

### ISSUE THREAD

**Issue by Digital-Foundry** [dartungar/obsidian-mermaid#15]
when I use the mermaid toolbar it does not paste the code block in the note and when I try to write it manually it gives me this error. 

```
Error parsing Mermaid diagram!

Parse error on line 2:

^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'EOF'
```

**Comment by dartungar** [comment]
@Digital-Foundry hey there! This error indicates some sort of error in the diagram syntax. This plugin has no control over it, the only thing you can do is make sure the syntax is correct. You can use the link to official documentation to look at examples and see if your syntax matches them:
![image](https://user-images.githubusercontent.com/36126057/219844862-06b50620-d662-4dee-b4cf-93833bbb1885.png)
