### ISSUE TITLE
Error parsing Mermaid diagram!

### ISSUE THREAD

**Issue by berezovskyi-oleksandr** [dartungar/obsidian-mermaid#16]
I tried to paste the example from the Mermaid [documentation](https://mermaid.js.org/syntax/sequenceDiagram.html#grouping-box) and it doesn't work correctly. I suppose that `box` is not parsed correctly
![image](https://user-images.githubusercontent.com/221562/221558893-aeac2e48-df60-4a56-91f4-d7fef27162f8.png)

I've tried to paste the same code to the [online editor](https://mermaid.live/edit#pako:eNplkMFOxCAQhl9lnIOn-gIc1tCaaHoy8cplFkZLpIAUos1m311WbDbZciL_fN8MzAl1MIwCoZ6Fvwp7zU-WPhLNyl_CY_iB15KiY5DOaoZ7GMPkWzFSylbbSD6D3Edji9ibay_pQ544wXMKJe6Vfh8NN13kw-EwCnhh58LfWzqYwjdQYlhDeWzQWCEp6hSmfHf1-s3rw7FpdoFhouRW-Df7ig0b1kq3A7DDmdNM1tTNnS6awvqpmRWKejWUPhUqf64clRzeVq9R5FS4wxIN5W3DKN7JLXz-Bbahe3s) and it works just fine:
![image](https://user-images.githubusercontent.com/221562/221559410-6f9d1ab5-4cd7-491f-996b-71e33d28a12f.png)

**Comment by dartungar** [comment]
@berezovskyi-oleksandr the plugin has no control over Obsidian's Mermaid rendering, so official version may have gone ahead of Obsidian's. Nothing we can do about that but wait!
