### ISSUE TITLE
Directed graph becomes undirected when exporting to PDF

### ISSUE THREAD

**Issue by AndersonALAC** [dartungar/obsidian-mermaid#17]
I'm using obsidian on macOS, directed graphs look quite normal with arrows in live preview mode, but turns undirected when switching to reading mode or export to PDF, I don't think this should be expected.

<img width="662" alt="Screenshot 2023-03-07 at 17 40 21" src="https://user-images.githubusercontent.com/43598111/223504580-4b203760-38ae-47dc-ade1-8b5d44254605.png">
<img width="661" alt="Screenshot 2023-03-07 at 17 40 14" src="https://user-images.githubusercontent.com/43598111/223504589-207c4fc9-118d-4bce-9b8d-b33a8419cf4d.png">
<img width="173" alt="Screenshot 2023-03-07 at 17 41 51" src="https://user-images.githubusercontent.com/43598111/223504599-6308eb5d-0853-42f2-bd8f-a51d24763a12.png">

**Comment by dartungar** [comment]
@AndersonALAC this looks like a bug in Obsidian's mermaid support (my plugin has no control over this). Please consider reporting it on official forums!
