### ISSUE TITLE
Support for Mindmaps

### ISSUE THREAD

**Issue by carlhall-db** [dartungar/obsidian-mermaid#26]
Mermaid introduced mindmaps. Though marked as `experimental`, the docs note: "The syntax is stable except for the icon integration which is the experimental part."
Reference: https://mermaid.js.org/syntax/mindmap.html

When I try to create a mindmap in a Mermaid code block, I get the following message:
> Error parsing Mermaid diagram!
> 
> No diagram type detected for text: mindmap

**Comment by dartungar** [comment]
Unfortunately there's nothing I can do about it - the plugin only adds toolbar & tools, and has no control of Obsidian's mermaid version :( 
Please see #12 for details.
