### ISSUE TITLE
Unable to display all content

### ISSUE THREAD

**Issue by shadedcastle** [dartungar/obsidian-mermaid#27]
First of all, thanks for this amazing plugin!

I view class diagrams in Meraid doc. in Defining Relationship chapter.
I copy example code to obsidian. after renderer render the code, The image has been truncated.
It include class M N O P, but they didn't display in image.I attempted to zoom in and out using ctrl.But it's useless.
Maybe it could add move and zoom function.

link is [Defining Relationship](https://mermaid.js.org/syntax/classDiagram.html#defining-relationship)
The code is not far behind the title.

code:
```
classDiagram
classA <|-- classB
classC *-- classD
classE o-- classF
classG <-- classH
classI -- classJ
classK <.. classL
classM <|.. classN
classO .. classP
```

**Comment by dartungar** [comment]
@shadedcastle please remember that this plugin has no control over how Obsidian renders mermaid! So, unfortunately, I can't help with this problem. It's best to raise this issue in official Obsidian forums.
