### ISSUE TITLE
Adding "top to bottom" tag in gitgraph breaks preview

### ISSUE THREAD

**Issue by Jonathan-Zollinger** [dartungar/obsidian-mermaid#31]
## Summary
attempting to use the `TB` tag in gitGraph to change the diagram orientation causes the preview to display an error.

## Expected Behavior
The diagram renders either in the normal orientation or new orientation with the `TB` tag, like seen in the svg output from mermaid live
<details><summary>svg</summary>

![mermaid-diagram-2023-08-02-005556](https://github.com/dartungar/obsidian-mermaid/assets/62955101/509685e1-07b9-4306-92ce-e464fd29c4ca)
</details>

## Current Behavior
Adding `TB:` to a gitGraph causes an error to read out. I've included the error message below.

<details><summary>Error Message</summary>

```sh
Error parsing Mermaid diagram!

Parse error on line 3:
...e1'}} }%%gitGraph TB:	commit id: "Ame
---------------------^
Expecting 'EOF', ':', 'DIR', 'NL', got 'ID'
```
</details>
<details><summary>Mermaid Code</summary>

```mermaid
---
title: Metropolitan line
---
%%{init: { 'logLevel': 'debug', 'theme': 'dark', 'gitGraph': {'showBranches': true, 'showCommitLabel':true,'mainBranchName': 'MetroLine1'}} }%%
gitGraph TB:
	commit id: "Amersham" type: HIGHLIGHT tag: "starts here"
    commit id: "stop"
    commit id: "stop 1"
    commit id: "stop 2"
    commit id: "stop 3"
    commit id: "stop 4"
    commit id: "stop 5"
    commit id: "stop 6"
    commit id: "stop 7"
    commit id: "stop 8"
    commit id: "stop 9"
    commit id: "stop 10"
    commit id: "stop 11"
    commit id: "stop 12" type: HIGHLIGHT tag: "change lines"
    branch "Jubilee"
	commit id: "Swiss Cottage"
	commit id: "St. John's Wood"
	commit id: "Baker Street"
	commit id: "Bond Street"
	commit id: "Green Park"
	commit id: "Westminster"
	commit id: "Waterloo"
	commit id: "Southwark"
```

</details>

## Steps to reproduce
 
1. produce a functioning gitgraph functioning git graph

```mermaid
---
title: Metropolitan line
---
%%{init: { 'logLevel': 'debug', 'theme': 'dark', 'gitGraph': {'showBranches': true, 'showCommitLabel':true,'mainBranchName': 'MetroLine1'}} }%%
gitGraph
	commit id: "Amersham" type: HIGHLIGHT tag: "starts here"
    commit id: "stop"
    commit id: "stop 1"
    commit id: "stop 2"
    commit id: "stop 3"
    commit id: "stop 4"
    commit id: "stop 5"
    commit id: "stop 6"
    commit id: "stop 7"
    commit id: "stop 8"
    commit id: "stop 9"
    commit id: "stop 10"
    commit id: "stop 11"
    commit id: "stop 12" type: HIGHLIGHT tag: "change lines"
    branch "Jubilee"
	commit id: "Swiss Cottage"
	commit id: "St. John's Wood"
	commit id: "Baker Street"
	commit id: "Bond Street"
	commit id: "Green Park"
	commit id: "Westminster"
	commit id: "Waterloo"
	commit id: "Southwark"
```

2. Attempt to append ` TB:` to `gitGraph` per [the docs](https://mermaid.js.org/syntax/gitgraph.html#orientation-v10-3-0)

**Comment by dartungar** [comment]
@Jonathan-Zollinger hi, thanks for the best bug report in a while! But please remember that this plugin has no control over how Obsidian renders mermaid :( So, unfortunately, I can't help with this problem. It's best to raise this issue in official Obsidian forums.
