### ISSUE TITLE
Add support for `quadrantChart`

### ISSUE THREAD

**Issue by jmg-duarte** [dartungar/obsidian-mermaid#32]
As it stands, `quadrantChart` (https://mermaid.js.org/syntax/quadrantChart.html) is not detected as a valid Mermaid.

```
quadrantChart
	title test
	x-axis Backwards --> Fowards Compatibility
	x-axis Backwards --> Fowards Compatibility
	quadrant-1 a
	quadrant-2 b
	quadrant-3 c
	quadrant-4 d
```

**Comment by dartungar** [comment]
@jmg-duarte thanks for the suggestion! Please remember that this plugin has no control over how Obsidian renders mermaid, so this type of chart will be supported when Obsidian updates its Mermaid version to that which supports it.

**Comment by dartungar** [comment]
@superkeyor Mermaid Tools 1.1.0 now has Quadrant Chart and sample diagrams!
