### ISSUE TITLE
Mermaid sidemenu suddenly disappeared

### ISSUE THREAD

**Issue by rafaelbressan** [dartungar/obsidian-mermaid#33]
I am having an issue with Mermaid Tools where the side menu simply stopped showing the options.

See image above:

![image](https://github.com/dartungar/obsidian-mermaid/assets/31864534/1d0e3290-3422-4bba-ba02-cd17a881975a)

It has been like this after a while and I actually don't know what happened to not show any options anymore.

I've tried:
- Removing all CSS snippets and theme related plugins;
- Disabling several community plugins with debugging community plugins;
- Inspecting the content to see if anything could be changed, such as a `display` property;
- Opening only the mermaid tools plugin in a dummy vault without any custom CSS;

**Is there something happening or is it just me?**
PS: I am using Catalyst version, I don't know if it has some conflict with the Plugin.

**Comment by dartungar** [comment]
@rafaelbressan it seems some update of Obsidian broke the way the plugin renders mermaid in sidebar and settings.
Will look into that soon

**Comment by johnoscott** [comment]
I am having this issue also. Please fix.

**Comment by dartungar** [comment]
@johnoscott @rafaelbressan this fix will take some time, because Mermaid changed how it renders stuff in v.10. Good news is that it's not broken for Obsidian < 1.4.

**Comment by dartungar** [comment]
will be fixed in https://github.com/dartungar/obsidian-mermaid/releases/tag/1.0.0

**Comment by WaYdotNET** [comment]
<img width="962" alt="Screenshot 2023-08-24 at 14 39 05" src="https://github.com/dartungar/obsidian-mermaid/assets/197466/0710ba2d-3068-48e5-8807-585a83c1608c">


With version 1.0.0 , ' have this issue
<img width="365" alt="Screenshot 2023-08-24 at 14 39 13" src="https://github.com/dartungar/obsidian-mermaid/assets/197466/3a033da0-ddfe-410d-b844-b52ac3894ea6">

**Comment by dartungar** [comment]
@WaYdotNET what version of Obsidian do you have?

**Comment by WaYdotNET** [comment]
1.3.7 (installer version: 1.3.4)

**Comment by EmersonDing** [comment]
@dartungar any plan to fix it in later obsidian version?

**Comment by WaYdotNET** [comment]
@dartungar some problem.
when i search plugin ...
<img width="489" alt="Screenshot 2023-08-25 at 07 53 05" src="https://github.com/dartungar/obsidian-mermaid/assets/197466/bbf77ceb-df66-4b00-a655-1fb111ce58c0">

**Comment by dartungar** [comment]
@EmersonDing it is fixed for versions >1.4.0. Unfortunately this is "either-or" situation, and since "MinAppVersion" property does not work, there's nothing I can do - all you have to do is wait for 1.4.0 to become public.

**Comment by dartungar** [comment]
Since there's no easy way I can make the plugin work for both Obsidian >1.4 and <1.4, I've set the latest version of the plugin to be 0.2.2 again, until Obsidian 1.4 makes it to public.

If you are experiencing issues with Obsidian 1.4, please download plugin files for version 1.0.0 from Releases page and place them into plugin directory.
