### ISSUE TITLE
C4Context fontColor being ignored

### ISSUE THREAD

**Issue by MiPnamic** [dartungar/obsidian-mermaid#34]
I just created a C4Context diagram and when I try to change the default colours it keeps ignoring the fontColor parameter.

```
mermaid
C4Context
	title Example
	
	System(object, "Sample object")
	
	UpdateElementStyle(object, $fontColor="white", $bgColor="lightgrey")
```

result:
<img width="370" alt="image" src="https://github.com/dartungar/obsidian-mermaid/assets/1021567/ac50384d-062a-4f3b-a423-af63cc1c6eb7">

**Comment by MiPnamic** [comment]
The problem with raising it inside the Obsidian forum is that while trying to fill in a bug, it said that they accept only bug reports that do not involve plugins... pretty frustating.

**Comment by dartungar** [comment]
@MiPnamic but it does not involve the plugin! Obsidian supports Mermaid natively, see https://help.obsidian.md/Editing+and+formatting/Advanced+formatting+syntax#Diagram.
