### ISSUE TITLE
Mermaid toolbar shows "undefined" for all elements

### ISSUE THREAD

**Issue by EmersonDing** [dartungar/obsidian-mermaid#36]
Example below:
<img width="287" alt="image" src="https://github.com/dartungar/obsidian-mermaid/assets/10276558/76dc9959-c653-4e5b-88f1-71f08d91ae96">

Mermaid tool version: 1.0.0
Obsidian version: 1.3.7
OS: MacOS Ventura 13.5

**Comment by Lignaloes** [comment]
I am in windows system and I have encountered the same problem

**Comment by dartungar** [comment]
@EmersonDing @Lignaloes I've reverted latest actual version to 0.2.2, please reinstall the plugin.
