### ISSUE TITLE
Changes in elements are not saved

### ISSUE THREAD

**Issue by QuanPie** [dartungar/obsidian-mermaid#42]
System OS: MacOS 14.0
Obsidian version: 1.4.16
Plugin version: 1.1.0
Describe: The content couldn't save, while adding a new element.

And thank you for creating this awesome plugin~

**Comment by dartungar** [comment]
@QuanPie hey, thanks for the kind words! I've just tried adding an element and it worked, so it might not be a general issue.
Could you provide some details? Like content of an element and type, and maybe open console (Ctrl+Shift+i) and see if any error pops up when element fails to save?

**Comment by QuanPie** [comment]
Thank you for replying, here's what I did while I am trying to add a new element. And the same situation occurred in the sandbox mode.
---
1. I add new element first, and save it.
<img width="566" alt="image" src="https://github.com/dartungar/obsidian-mermaid/assets/47452844/920a9c82-512f-40ef-823b-9d0ec16aa79b">

2. looks like it saved well.
<img width="1394" alt="image" src="https://github.com/dartungar/obsidian-mermaid/assets/47452844/e33eda42-7dcd-45e1-b8a6-ec0b105e1c74">

3. But I checked the new element again, it didn't saved properly.
<img width="571" alt="image" src="https://github.com/dartungar/obsidian-mermaid/assets/47452844/cd6aaf04-41b4-4d92-bef0-96d4b53d8701">

**Comment by dartungar** [comment]
@QuanPie should be fixed in 1.1.1
