### ISSUE TITLE
How to open an obsidian note?

### ISSUE THREAD

**Issue by nerkuda** [dartungar/obsidian-mermaid#48]
Hi

How do I open another obsidian note by clicking on the diagram node?

```
a --> BB

click B "<???>"
```
How do I link to a vault file instead of an URL? What should I write instead of `<???>`?

**Comment by dartungar** [comment]
@nerkuda hey, you probably need note's internal URL for that.
To get it, open command palette and select "Copy Obsidian URL" (while you are on the note you want to link to).
The URL would be like `obsidian://open?vault=notes&file=04%20archive%2Fjournal%2Fweekly%20journal%2F2024-W07`.
Don't know if it will work with Mermaid though.

**Comment by nerkuda** [comment]
@dartungar 
I thought so too. If it worked, I wouldn't ask.

**Comment by dartungar** [comment]
I suggest taking the issue on official Obsidian forums or Discord. Not sure
I know how to do that.
