### ISSUE TITLE
[Feature Request] Add all the other elements supported by mermaid's flowchart

### ISSUE THREAD

**Issue by Thiago-Morais** [dartungar/obsidian-mermaid#51]
The mermaid's flowchart supports many other elements that are not included in the default elements list
like:
- [Other shapes](https://mermaid.js.org/syntax/flowchart.html#node-shapes):
  - [Hexagon](https://mermaid.js.org/syntax/flowchart.html#a-hexagon-node)
  - [Parallelogram](https://mermaid.js.org/syntax/flowchart.html#parallelogram)
  - [Double circle](https://mermaid.js.org/syntax/flowchart.html#double-circle)
  - etc
- [Other link types:](https://mermaid.js.org/syntax/flowchart.html#links-between-nodes)
  - [Open link](https://mermaid.js.org/syntax/flowchart.html#an-open-link)
  - [Invisible link](https://mermaid.js.org/syntax/flowchart.html#an-invisible-link)
- [Arrow heads:](https://mermaid.js.org/syntax/flowchart.html#new-arrow-types)
  - [Circle edge](https://mermaid.js.org/syntax/flowchart.html#circle-edge-example)
  - [Cross edge](https://mermaid.js.org/syntax/flowchart.html#cross-edge-example)

So my suggestion is to add all supported element in the default elements list.

**Comment by dartungar** [comment]
the new elements are added in 1.1.3. Cheers!
