### ISSUE TITLE
Feature Request: Adjust branch stroke width and branch spacing

### ISSUE THREAD

**Issue by cryoden** [dartungar/obsidian-mermaid#53]
Thanks for bringing the plugin to obsidian. I was looking for a way to adjust the branch line weight/stroke width and branch spacing within css but without luck. Can you please make it possible? 
The branches are rendering very large, and I think it would be nice to customize them to fit notes. 
If not, can I modify some part of  the source, define there the styling and compile a version of the plugin for myself?

**Comment by dartungar** [comment]
@cryoden hey, thanks for the suggestion!
Unfortunately I have no way of controlling how Mermaid is rendered - this is done by Obsidian itself. Maybe try posting this on official forums?
