### ISSUE TITLE
LaTeX and KaTeX are missing

### ISSUE THREAD

**Issue by Luke-Sims** [dartungar/obsidian-mermaid#54]
I've tried to implement Katex code in mermaid on obsidian.
according to the Mermaid [documentation](https://mermaid.js.org/config/math.html) I should be able to use this kind of command on Katex:
```
 graph LR
      A["$$x^2$$"] -->|"$$\sqrt{x+3}$$"| B("$$\frac{1}{2}$$")
      A -->|"$$\overbrace{a+b+c}^{\text{note}}$$"| C("$$\pi r^2$$")
      B --> D("$$x = \begin{cases} a &\text{if } b \\ c &\text{if } d \end{cases}$$")
      C --> E("$$x(t)=c_1\begin{bmatrix}-\cos{t}+\sin{t}\\ 2\cos{t} \end{bmatrix}e^{2t}$$")
```
but when I implement it on obsidian I got this:
![Screenshot from 2024-11-02 10-45-57](https://github.com/user-attachments/assets/2bcfb39d-bb1d-4355-a3ad-6fd42d72c45c)

**Comment by dartungar** [comment]
@Luke-Sims sorry, I can't really help here ☹️ as per this plugin's readme:
> Please note that rendering Mermaid is Obsidian's feature, and not implemented by this plugin. This plugin has no control over how Mermaid is rendered. All bugs concerning rendering of diagrams should be posted to official forums.
