### ISSUE TITLE
Feature-Request: Image size

### ISSUE THREAD

**Issue by cschaba** [dartungar/obsidian-mermaid#55]
Thanks for the plugin.  It is really helpful.

Is there a way to scale the image to fit e.g. to a PDF Export?

I have a diagram that's too wide to fit to regular paper, but I would be ok when there would be an option to lets say scale it to 90% of page width...

**Comment by dartungar** [comment]
@cschaba sadly this plugin doesn't have control over how Mermaid is rendered :( it's done by Obsidian itself.
I wonder if a plugin like https://github.com/l1xnan/obsidian-better-export-pdf could resolve your issue? It seems to have an option for something like what you need 🤔
