### ISSUE TITLE
Choose diagram type when inserting new Mermaid code block

### ISSUE THREAD

**Issue by swehba** [dartungar/obsidian-mermaid#7]
Love the idea behind the tool, but it's not as intuitive as it might be. If I am doing things correctly, to create a new UML class diagram, you first click on **insert empty Mermaid code block**, you then move the cursor inside the code block and insert a new element by clicking on it in the Mermaid panel. However, this does not render correctly. The code block also needs a diagram specifier such as "classDiagram". It would be nice to if the **insert empty Mermaid code block** allowed you to choose the diagram type.

**Comment by dartungar** [comment]
@swehba agreed, this part does need UX improvements. For first iteration, I will probably improve 'paste code block' so it will paste some kind of default diagram of currently selected type.

**Comment by dartungar** [comment]
Out in 0.1.0.
